export const productFilterableFields: string[] = [
  'productName',
  'category',
  'description',
  'keyFeatures',
  'searchTerm',
  'price',
  'status',
  'battery',
  'brand',
  'model',
  'os',
  'camera',
  'size',
  'storage',
  'quantity',
  'max',
];
export const productSearchableFields: string[] = [
  // 'productName',
  // 'category',
  // 'description',
  // 'keyFeatures',
  // 'battery',
  // 'brand',
  'model',
  // 'os',
  // 'camera',
  // 'size',
  // 'storage',
  // 'quantity',
];
